"""Hand-written (non-LLM) content for the SCHD demo.

Written directly by Claude instead of generated by Gemini, so the demo can
show real, good-quality Docker-rendered videos without spending API quota.
Wired into pipeline/mock_llm.py, which detects these topics and serves this
content instead of its generic filler.
"""

SCHD_BASE_TOPIC_PROMPT = (
    "Explain how the Schwab U.S. Dividend Equity ETF (SCHD) works for a "
    "beginner investor: its 0.06% expense ratio, its quarterly dividend "
    "distributions, and how it selects holdings by tracking the Dow Jones "
    "U.S. Dividend 100 Index."
)

SCHD_HIGHER_FEE_TOPIC_PROMPT = (
    "Explain how an investor's long-run returns in a fund like the Schwab "
    "U.S. Dividend Equity ETF (SCHD) would differ if its expense ratio were "
    "0.75% instead of its actual 0.06%, holding everything else the same."
)

SCHD_REINVEST_TOPIC_PROMPT = (
    "Explain how reinvesting every quarterly dividend from a fund like the "
    "Schwab U.S. Dividend Equity ETF (SCHD) compounds an investment's growth "
    "over time compared to taking the dividends as cash."
)

SCHD_START_EARLIER_TOPIC_PROMPT = (
    "Explain how starting to invest in a dividend fund like the Schwab U.S. "
    "Dividend Equity ETF (SCHD) 5 years earlier than today changes the total "
    "dividends received and the compounding effect by now."
)

TOPIC_PROMPTS = {
    "schd_how_it_works": SCHD_BASE_TOPIC_PROMPT,
    "schd_higher_fee": SCHD_HIGHER_FEE_TOPIC_PROMPT,
    "schd_reinvest": SCHD_REINVEST_TOPIC_PROMPT,
    "schd_start_earlier": SCHD_START_EARLIER_TOPIC_PROMPT,
}

PLANS = {
    "schd_how_it_works": {
        "title": "How SCHD Works",
        "slug": "schd_how_it_works",
        "scenes": [
            {
                "id": 1,
                "goal": "Introduce SCHD as a dividend-focused ETF",
                "visuals": ["SCHD ticker badge", "subtitle: dividend-focused ETF"],
                "narration": "SCHD is an ETF built around one idea: pay you steady, growing dividends from quality companies.",
                "duration_sec": 6,
            },
            {
                "id": 2,
                "goal": "Show how small the 0.06% expense ratio is",
                "visuals": ["a thin bar labeled SCHD 0.06%", "a taller bar labeled typical fund ~0.5%"],
                "narration": "Its expense ratio is 0.06% a year - on ten thousand dollars, that's about six dollars, far less than a typical fund's fee.",
                "duration_sec": 7,
            },
            {
                "id": 3,
                "goal": "Show the quarterly dividend rhythm and index-based holding selection",
                "visuals": ["a year timeline with four dividend ticks", "a row of squares representing index holdings"],
                "narration": "Four times a year, SCHD pays out dividends collected from the roughly one hundred quality dividend payers it tracks in the Dow Jones U.S. Dividend 100 Index.",
                "duration_sec": 7,
            },
        ],
    },
    "schd_higher_fee": {
        "title": "The Cost of Fees",
        "slug": "schd_higher_fee",
        "scenes": [
            {
                "id": 1,
                "goal": "Introduce the fee comparison",
                "visuals": ["title card", "subtitle comparing 0.06% and 0.75%"],
                "narration": "What if a fund like SCHD charged 0.75% instead of 0.06%? Let's see what that costs over time.",
                "duration_sec": 6,
            },
            {
                "id": 2,
                "goal": "Show two growth curves diverging over 30 years due to fee drag",
                "visuals": ["axes with years on x and dollars on y", "a low-fee growth curve", "a high-fee growth curve"],
                "narration": "Ten thousand dollars, growing for thirty years - the low-fee line pulls ahead of the high-fee line more and more each year.",
                "duration_sec": 8,
            },
            {
                "id": 3,
                "goal": "State the final dollar gap and the takeaway",
                "visuals": ["final value for the low-fee case", "final value for the high-fee case", "a one-line insight"],
                "narration": "By year thirty, that fee difference is worth over ten thousand dollars - small annual fees compound into big gaps.",
                "duration_sec": 7,
            },
        ],
    },
    "schd_reinvest": {
        "title": "The Power of Reinvesting Dividends",
        "slug": "schd_reinvest",
        "scenes": [
            {
                "id": 1,
                "goal": "Introduce reinvesting vs. taking dividends as cash",
                "visuals": ["title card", "subtitle: cash out vs. reinvest"],
                "narration": "Every quarter, SCHD pays a dividend. What happens if you reinvest it instead of taking it as cash?",
                "duration_sec": 6,
            },
            {
                "id": 2,
                "goal": "Show reinvested growth compounding faster than cash payouts",
                "visuals": ["axes with years on x and dollars on y", "a reinvested growth curve", "a cash-payout growth curve"],
                "narration": "Reinvested dividends buy more shares, which pay their own dividends - the curve pulls further ahead every year.",
                "duration_sec": 8,
            },
            {
                "id": 3,
                "goal": "State the final gap and the compounding insight",
                "visuals": ["final value reinvested", "final value cash payout", "a one-line insight"],
                "narration": "Over thirty years, reinvesting more than doubles the outcome - each dividend starts earning its own dividends.",
                "duration_sec": 7,
            },
        ],
    },
    "schd_start_earlier": {
        "title": "Why Starting Earlier Matters",
        "slug": "schd_start_earlier",
        "scenes": [
            {
                "id": 1,
                "goal": "Introduce the five-year head start comparison",
                "visuals": ["title card", "subtitle: same investor, five years apart"],
                "narration": "Same investor, same ten thousand dollars - what if they'd started five years earlier?",
                "duration_sec": 6,
            },
            {
                "id": 2,
                "goal": "Show two growth curves offset by five years",
                "visuals": ["axes with years on x and dollars on y", "a curve starting at year zero", "a curve starting five years later"],
                "narration": "One curve starts investing right away. The other waits five years before starting - watch how far behind it stays.",
                "duration_sec": 8,
            },
            {
                "id": 3,
                "goal": "State the final gap and the time-in-market insight",
                "visuals": ["final value for the early starter", "final value for the late starter", "a one-line insight"],
                "narration": "Five extra years of compounding is worth over twenty thousand dollars here - time in the market matters.",
                "duration_sec": 7,
            },
        ],
    },
}


def _scene(slug: str, body: str) -> str:
    return f"# SCHD_SLUG: {slug}\n{body}"


SCENES = {
    ("schd_how_it_works", 1): _scene(
        "schd_how_it_works",
        '''from manim import *


class Scene1(Scene):
    def construct(self):
        ticker = Text("SCHD", font_size=56, color=YELLOW)
        subtitle = Text("A Dividend-Focused ETF", font_size=28, color=GRAY)
        subtitle.next_to(ticker, DOWN, buff=0.4)
        self.play(Write(ticker))
        self.play(FadeIn(subtitle))
        self.wait(1)
''',
    ),
    ("schd_how_it_works", 2): _scene(
        "schd_how_it_works",
        '''from manim import *


class Scene2(Scene):
    def construct(self):
        title = Text("How Small Is the Fee?", font_size=40).to_edge(UP)
        self.play(Write(title))

        schd_bar = Rectangle(width=1.4, height=0.3, color=YELLOW, fill_color=YELLOW, fill_opacity=0.9)
        schd_text = Text("SCHD: 0.06%", font_size=24)
        schd_group = VGroup(schd_bar, schd_text).arrange(DOWN, buff=0.3)

        typical_bar = Rectangle(width=1.4, height=2.5, color=RED, fill_color=RED, fill_opacity=0.9)
        typical_text = Text("Typical fund: ~0.5%", font_size=24)
        typical_group = VGroup(typical_bar, typical_text).arrange(DOWN, buff=0.3)

        bars = VGroup(schd_group, typical_group).arrange(RIGHT, buff=1.5, aligned_edge=DOWN)
        bars.next_to(title, DOWN, buff=1)

        caption = Text("On $10,000 a year: roughly $6 vs $50", font_size=22, color=GRAY)
        caption.next_to(bars, DOWN, buff=0.6)

        self.play(FadeIn(bars))
        self.play(Write(caption))
        self.wait(1)
''',
    ),
    ("schd_how_it_works", 3): _scene(
        "schd_how_it_works",
        '''from manim import *


class Scene3(Scene):
    def construct(self):
        title = Text("Paid Quarterly, From ~100 Companies", font_size=32).to_edge(UP)
        self.play(Write(title))

        line = Line(LEFT * 4, RIGHT * 4)
        ticks = VGroup()
        labels = VGroup()
        for i, q in enumerate(["Q1", "Q2", "Q3", "Q4"]):
            x = -3 + i * 2
            tick = Line(UP * 0.2, DOWN * 0.2).move_to([x, 0, 0])
            label = Text(q, font_size=22).next_to(tick, DOWN, buff=0.3)
            ticks.add(tick)
            labels.add(label)
        timeline = VGroup(line, ticks, labels)
        timeline.next_to(title, DOWN, buff=1)

        holdings = VGroup(*[Square(side_length=0.4, color=BLUE, fill_color=BLUE, fill_opacity=0.6) for _ in range(10)])
        holdings.arrange(RIGHT, buff=0.15)
        holdings_label = Text("~100 quality dividend payers", font_size=22, color=GRAY)
        holdings_group = VGroup(holdings, holdings_label).arrange(DOWN, buff=0.3)
        holdings_group.next_to(timeline, DOWN, buff=1)

        self.play(Create(line), FadeIn(ticks), Write(labels))
        self.wait(0.3)
        self.play(FadeIn(holdings_group))
        self.wait(1)
''',
    ),
    ("schd_higher_fee", 1): _scene(
        "schd_higher_fee",
        '''from manim import *


class Scene1(Scene):
    def construct(self):
        title = Text("The Cost of Fees", font_size=44)
        subtitle = Text("0.06% vs 0.75% expense ratio", font_size=26, color=GRAY)
        subtitle.next_to(title, DOWN, buff=0.4)
        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1)
''',
    ),
    ("schd_higher_fee", 2): _scene(
        "schd_higher_fee",
        '''from manim import *


class Scene2(Scene):
    def construct(self):
        title = Text("$10,000 Over 30 Years", font_size=36).to_edge(UP)
        self.play(Write(title))

        axes = Axes(x_range=[0, 30, 10], y_range=[0, 80000, 20000], x_length=7, y_length=4)
        axes.next_to(title, DOWN, buff=0.4)

        low_fee_curve = axes.plot(lambda x: 10000 * (1.07 ** x), x_range=[0, 30], color=YELLOW)
        high_fee_curve = axes.plot(lambda x: 10000 * (1.0631 ** x), x_range=[0, 30], color=RED)

        low_label = Text("0.06% fee", font_size=22, color=YELLOW)
        high_label = Text("0.75% fee", font_size=22, color=RED)
        legend = VGroup(low_label, high_label).arrange(RIGHT, buff=1)
        legend.next_to(axes, DOWN, buff=0.3)

        self.play(Create(axes))
        self.play(Create(low_fee_curve), Create(high_fee_curve))
        self.play(Write(legend))
        self.wait(1)
''',
    ),
    ("schd_higher_fee", 3): _scene(
        "schd_higher_fee",
        '''from manim import *


class Scene3(Scene):
    def construct(self):
        title = Text("The Gap Adds Up", font_size=40).to_edge(UP)
        self.play(Write(title))

        low_final = Text("0.06% fee: ~$76,000", font_size=28, color=YELLOW)
        high_final = Text("0.75% fee: ~$63,000", font_size=28, color=RED)
        values = VGroup(low_final, high_final).arrange(DOWN, buff=0.5)
        values.next_to(title, DOWN, buff=1)

        insight = Text("A 0.69% fee difference costs over $12,000 here.", font_size=24, color=GRAY)
        insight.next_to(values, DOWN, buff=0.8)

        self.play(FadeIn(values))
        self.play(Write(insight))
        self.wait(1)
''',
    ),
    ("schd_reinvest", 1): _scene(
        "schd_reinvest",
        '''from manim import *


class Scene1(Scene):
    def construct(self):
        title = Text("The Power of Reinvesting", font_size=42)
        subtitle = Text("Cash out vs. reinvest every dividend", font_size=26, color=GRAY)
        subtitle.next_to(title, DOWN, buff=0.4)
        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1)
''',
    ),
    ("schd_reinvest", 2): _scene(
        "schd_reinvest",
        '''from manim import *


class Scene2(Scene):
    def construct(self):
        title = Text("$10,000 Over 30 Years", font_size=36).to_edge(UP)
        self.play(Write(title))

        axes = Axes(x_range=[0, 30, 10], y_range=[0, 80000, 20000], x_length=7, y_length=4)
        axes.next_to(title, DOWN, buff=0.4)

        reinvest_curve = axes.plot(lambda x: 10000 * (1.07 ** x), x_range=[0, 30], color=GREEN)
        cash_curve = axes.plot(lambda x: 10000 * (1.04 ** x), x_range=[0, 30], color=GRAY)

        reinvest_label = Text("Reinvested", font_size=22, color=GREEN)
        cash_label = Text("Cash payout", font_size=22, color=GRAY)
        legend = VGroup(reinvest_label, cash_label).arrange(RIGHT, buff=1)
        legend.next_to(axes, DOWN, buff=0.3)

        self.play(Create(axes))
        self.play(Create(reinvest_curve), Create(cash_curve))
        self.play(Write(legend))
        self.wait(1)
''',
    ),
    ("schd_reinvest", 3): _scene(
        "schd_reinvest",
        '''from manim import *


class Scene3(Scene):
    def construct(self):
        title = Text("Compounding Wins", font_size=40).to_edge(UP)
        self.play(Write(title))

        reinvest_final = Text("Reinvested: ~$76,000", font_size=28, color=GREEN)
        cash_final = Text("Cash payout: ~$32,000", font_size=28, color=GRAY)
        values = VGroup(reinvest_final, cash_final).arrange(DOWN, buff=0.5)
        values.next_to(title, DOWN, buff=1)

        insight = Text("Reinvesting lets each dividend start earning its own dividends.", font_size=22, color=GRAY)
        insight.next_to(values, DOWN, buff=0.8)

        self.play(FadeIn(values))
        self.play(Write(insight))
        self.wait(1)
''',
    ),
    ("schd_start_earlier", 1): _scene(
        "schd_start_earlier",
        '''from manim import *


class Scene1(Scene):
    def construct(self):
        title = Text("Why Starting Earlier Matters", font_size=38)
        subtitle = Text("Same investor, five years apart", font_size=26, color=GRAY)
        subtitle.next_to(title, DOWN, buff=0.4)
        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1)
''',
    ),
    ("schd_start_earlier", 2): _scene(
        "schd_start_earlier",
        '''from manim import *


class Scene2(Scene):
    def construct(self):
        title = Text("$10,000 Invested, 5 Years Apart", font_size=30).to_edge(UP)
        self.play(Write(title))

        axes = Axes(x_range=[0, 30, 10], y_range=[0, 80000, 20000], x_length=7, y_length=4)
        axes.next_to(title, DOWN, buff=0.4)

        early_curve = axes.plot(lambda x: 10000 * (1.07 ** x), x_range=[0, 30], color=BLUE)
        late_curve = axes.plot(lambda x: 10000 * (1.07 ** (x - 5)), x_range=[5, 30], color=ORANGE)

        early_label = Text("Started earlier", font_size=22, color=BLUE)
        late_label = Text("Started later", font_size=22, color=ORANGE)
        legend = VGroup(early_label, late_label).arrange(RIGHT, buff=1)
        legend.next_to(axes, DOWN, buff=0.3)

        self.play(Create(axes))
        self.play(Create(early_curve), Create(late_curve))
        self.play(Write(legend))
        self.wait(1)
''',
    ),
    ("schd_start_earlier", 3): _scene(
        "schd_start_earlier",
        '''from manim import *


class Scene3(Scene):
    def construct(self):
        title = Text("Five Years, One Big Gap", font_size=36).to_edge(UP)
        self.play(Write(title))

        early_final = Text("Started earlier: ~$76,000", font_size=28, color=BLUE)
        late_final = Text("Started later: ~$54,000", font_size=28, color=ORANGE)
        values = VGroup(early_final, late_final).arrange(DOWN, buff=0.5)
        values.next_to(title, DOWN, buff=1)

        insight = Text("Five extra years of compounding is worth over $20,000 here.", font_size=22, color=GRAY)
        insight.next_to(values, DOWN, buff=0.8)

        self.play(FadeIn(values))
        self.play(Write(insight))
        self.wait(1)
''',
    ),
}
